from FlagEmbedding import BGEM3FlagModel

from knowledgegraph.entity_align import EntityAlign

emdedding_model = BGEM3FlagModel(
    model_name_or_path=r".\bge_m3",
    normalize_embeddings=True,
    use_fp16=True,
)
aligner = EntityAlign(
    embedding_model=emdedding_model,
    threshold=0.525,  # 建议0.525，实验过的
    entity_direction=r".\test",
)

CANONICAL_ENTITIES = [
    # ================= 1. Process Parameters =================
    "Mold Temperature",
    "Melt Temperature",
    "Injection Pressure",
    "Packing Pressure",
    "Packing Time",
    "Injection Velocity",
    "Screw Rotation Speed",
    "Back Pressure",
    "Cooling Time",
    "Slow Shot Velocity",
    "Fast Shot Velocity",
    "Intensification Pressure",
    "Pressure Rise Time",
    "Cavity Vacuum Degree",
    "Pouring Temperature",
    "Plunger Stroke",
    # ================= 2. Defects =================
    "Gate Blushing",
    "Silver Streaks",
    "Gas Porosity",
    "Shrinkage Porosity",
    "Sink Marks",
    "Flash",
    "Short Shot",
    "Cold Shut",
    "Weld Lines",
    "Warpage",
    "Residual Stress",
    "Externally Solidified Crystals",
    "Flow Marks",
    "Blistering",
    # ================= 3. Materials & Alloys =================
    "Polycarbonate (PC)",
    "Polymethyl Methacrylate (PMMA)",
    "Polypropylene (PP)",
    "Acrylonitrile Butadiene Styrene (ABS)",
    "Polyamide 66 (PA66-GF30)",
    "AlSi10MnMg Aluminum Alloy",
    "A380 Aluminum Alloy",
    "ADC12 Aluminum Alloy",
    "AZ91D Magnesium Alloy",
    # ================= 4. Physical Mechanisms & Microstructures =================
    "Shear Thermal Degradation",
    "Molecular Chain Orientation",
    "Air Entrapment",
    "Filling Temperature Drop",
    "Solid Fraction",
    "Eutectic Silicon Phase",
    "Secondary Dendrite Arm Spacing",
    "Solid Solution Strengthening",
    "Age Hardening Precipitation",
]
# aligner.canonical_entity_embed(CANONICAL_ENTITIES)
aligner.index_read()

TEST_ENTITIES: list[tuple[str, str]] = [
    # ================= 1. 标准词直接命中 (Canonical Hits, 48条) =================
    ("Mold Temperature", "Mold Temperature"),
    ("Melt Temperature", "Melt Temperature"),
    ("Injection Pressure", "Injection Pressure"),
    ("Packing Pressure", "Packing Pressure"),
    ("Packing Time", "Packing Time"),
    ("Injection Velocity", "Injection Velocity"),
    ("Screw Rotation Speed", "Screw Rotation Speed"),
    ("Back Pressure", "Back Pressure"),
    ("Cooling Time", "Cooling Time"),
    ("Slow Shot Velocity", "Slow Shot Velocity"),
    ("Fast Shot Velocity", "Fast Shot Velocity"),
    ("Intensification Pressure", "Intensification Pressure"),
    ("Pressure Rise Time", "Pressure Rise Time"),
    ("Cavity Vacuum Degree", "Cavity Vacuum Degree"),
    ("Pouring Temperature", "Pouring Temperature"),
    ("Plunger Stroke", "Plunger Stroke"),
    ("Gate Blushing", "Gate Blushing"),
    ("Silver Streaks", "Silver Streaks"),
    ("Gas Porosity", "Gas Porosity"),
    ("Shrinkage Porosity", "Shrinkage Porosity"),
    ("Sink Marks", "Sink Marks"),
    ("Flash", "Flash"),
    ("Short Shot", "Short Shot"),
    ("Cold Shut", "Cold Shut"),
    ("Weld Lines", "Weld Lines"),
    ("Warpage", "Warpage"),
    ("Residual Stress", "Residual Stress"),
    ("Externally Solidified Crystals", "Externally Solidified Crystals"),
    ("Flow Marks", "Flow Marks"),
    ("Blistering", "Blistering"),
    ("Polycarbonate (PC)", "Polycarbonate (PC)"),
    ("Polymethyl Methacrylate (PMMA)", "Polymethyl Methacrylate (PMMA)"),
    ("Polypropylene (PP)", "Polypropylene (PP)"),
    ("Acrylonitrile Butadiene Styrene (ABS)", "Acrylonitrile Butadiene Styrene (ABS)"),
    ("Polyamide 66 (PA66-GF30)", "Polyamide 66 (PA66-GF30)"),
    ("AlSi10MnMg Aluminum Alloy", "AlSi10MnMg Aluminum Alloy"),
    ("A380 Aluminum Alloy", "A380 Aluminum Alloy"),
    ("ADC12 Aluminum Alloy", "ADC12 Aluminum Alloy"),
    ("AZ91D Magnesium Alloy", "AZ91D Magnesium Alloy"),
    ("Shear Thermal Degradation", "Shear Thermal Degradation"),
    ("Molecular Chain Orientation", "Molecular Chain Orientation"),
    ("Air Entrapment", "Air Entrapment"),
    ("Filling Temperature Drop", "Filling Temperature Drop"),
    ("Solid Fraction", "Solid Fraction"),
    ("Eutectic Silicon Phase", "Eutectic Silicon Phase"),
    ("Secondary Dendrite Arm Spacing", "Secondary Dendrite Arm Spacing"),
    ("Solid Solution Strengthening", "Solid Solution Strengthening"),
    ("Age Hardening Precipitation", "Age Hardening Precipitation"),
    # ================= 2. 英文变体/缩写/同义词 (English Variants, 147条) =================
    ("mold temp", "Mold Temperature"),
    ("die temperature", "Mold Temperature"),
    ("die temp", "Mold Temperature"),
    ("tooling temperature", "Mold Temperature"),
    ("mold temp setting", "Mold Temperature"),
    ("melt temp", "Melt Temperature"),
    ("barrel temperature", "Melt Temperature"),
    ("nozzle temperature", "Melt Temperature"),
    ("melt thermal state", "Melt Temperature"),
    ("liquidus temperature", "Melt Temperature"),
    ("injection pressure setting", "Injection Pressure"),
    ("inject press", "Injection Pressure"),
    ("first stage pressure", "Injection Pressure"),
    ("primary injection pressure", "Injection Pressure"),
    ("filling pressure", "Injection Pressure"),
    ("holding pressure", "Packing Pressure"),
    ("pack pressure", "Packing Pressure"),
    ("second stage pressure", "Packing Pressure"),
    ("hold press", "Packing Pressure"),
    ("dwell pressure", "Packing Pressure"),
    ("holding time", "Packing Time"),
    ("pack time", "Packing Time"),
    ("hold duration", "Packing Time"),
    ("dwell time", "Packing Time"),
    ("injection speed", "Injection Velocity"),
    ("ram speed", "Injection Velocity"),
    ("shot speed", "Injection Velocity"),
    ("filling velocity", "Injection Velocity"),
    ("ram velocity", "Injection Velocity"),
    ("screw speed", "Screw Rotation Speed"),
    ("screw RPM", "Screw Rotation Speed"),
    ("screw rate", "Screw Rotation Speed"),
    ("screw revolution", "Screw Rotation Speed"),
    ("screw back pressure", "Back Pressure"),
    ("back press", "Back Pressure"),
    ("counter pressure", "Back Pressure"),
    ("cooling duration", "Cooling Time"),
    ("cure time", "Cooling Time"),
    ("chill time", "Cooling Time"),
    ("mold cooling time", "Cooling Time"),
    ("slow shot speed", "Slow Shot Velocity"),
    ("first phase velocity", "Slow Shot Velocity"),
    ("slow plunger speed", "Slow Shot Velocity"),
    ("first stage speed", "Slow Shot Velocity"),
    ("fast shot speed", "Fast Shot Velocity"),
    ("second phase velocity", "Fast Shot Velocity"),
    ("fast plunger speed", "Fast Shot Velocity"),
    ("second stage speed", "Fast Shot Velocity"),
    ("intensifier pressure", "Intensification Pressure"),
    ("boost pressure", "Intensification Pressure"),
    ("multiplier pressure", "Intensification Pressure"),
    ("third phase pressure", "Intensification Pressure"),
    ("rise time", "Pressure Rise Time"),
    ("intensification build-up time", "Pressure Rise Time"),
    ("pressure ramp time", "Pressure Rise Time"),
    ("vacuum level", "Cavity Vacuum Degree"),
    ("die vacuum degree", "Cavity Vacuum Degree"),
    ("cavity vacuum", "Cavity Vacuum Degree"),
    ("evacuation pressure", "Cavity Vacuum Degree"),
    ("ladle temperature", "Pouring Temperature"),
    ("casting temperature", "Pouring Temperature"),
    ("molten metal pouring temperature", "Pouring Temperature"),
    ("shot stroke", "Plunger Stroke"),
    ("piston stroke", "Plunger Stroke"),
    ("plunger travel", "Plunger Stroke"),
    ("gate whitening", "Gate Blushing"),
    ("blushing", "Gate Blushing"),
    ("gate halo", "Gate Blushing"),
    ("gate stress whitening", "Gate Blushing"),
    ("silver marks", "Silver Streaks"),
    ("splay marks", "Silver Streaks"),
    ("silver streaks defect", "Silver Streaks"),
    ("moisture splay", "Silver Streaks"),
    ("air porosity", "Gas Porosity"),
    ("gas holes", "Gas Porosity"),
    ("blow holes", "Gas Porosity"),
    ("pinholes", "Gas Porosity"),
    ("shrinkage void", "Shrinkage Porosity"),
    ("micro-shrinkage", "Shrinkage Porosity"),
    ("shrinkage cavity", "Shrinkage Porosity"),
    ("macroporosity", "Shrinkage Porosity"),
    ("sink mark", "Sink Marks"),
    ("surface depression", "Sink Marks"),
    ("surface sink", "Sink Marks"),
    ("shrinkage mark", "Sink Marks"),
    ("burr", "Flash"),
    ("parting line flash", "Flash"),
    ("flashing defect", "Flash"),
    ("excess metal burr", "Flash"),
    ("underfill", "Short Shot"),
    ("short fill", "Short Shot"),
    ("incomplete fill", "Short Shot"),
    ("non-fill defect", "Short Shot"),
    ("cold lap", "Cold Shut"),
    ("cold run", "Cold Shut"),
    ("misrun defect", "Cold Shut"),
    ("cold shut seam", "Cold Shut"),
    ("knit lines", "Weld Lines"),
    ("meld lines", "Weld Lines"),
    ("welding line defect", "Weld Lines"),
    ("fusion line", "Weld Lines"),
    ("warping", "Warpage"),
    ("part distortion", "Warpage"),
    ("bending defect", "Warpage"),
    ("dimensional warpage", "Warpage"),
    ("internal stress", "Residual Stress"),
    ("molded-in stress", "Residual Stress"),
    ("frozen-in stress", "Residual Stress"),
    ("residual strain", "Residual Stress"),
    ("ESCs", "Externally Solidified Crystals"),
    ("externally formed crystals", "Externally Solidified Crystals"),
    ("pre-solidified crystals", "Externally Solidified Crystals"),
    ("solidified crystals in shot sleeve", "Externally Solidified Crystals"),
    ("wave marks", "Flow Marks"),
    ("ripple marks", "Flow Marks"),
    ("tiger stripes", "Flow Marks"),
    ("blister defect", "Blistering"),
    ("surface blistering", "Blistering"),
    ("thermal blisters", "Blistering"),
    ("PC resin", "Polycarbonate (PC)"),
    ("polycarbonate plastic", "Polycarbonate (PC)"),
    ("PMMA polymer", "Polymethyl Methacrylate (PMMA)"),
    ("acrylic plastic", "Polymethyl Methacrylate (PMMA)"),
    ("PP resin", "Polypropylene (PP)"),
    ("polypropylene material", "Polypropylene (PP)"),
    ("ABS resin", "Acrylonitrile Butadiene Styrene (ABS)"),
    ("ABS plastic", "Acrylonitrile Butadiene Styrene (ABS)"),
    ("PA66-GF30 material", "Polyamide 66 (PA66-GF30)"),
    ("glass filled nylon 66", "Polyamide 66 (PA66-GF30)"),
    ("AlSi10MnMg alloy", "AlSi10MnMg Aluminum Alloy"),
    ("A380 alloy", "A380 Aluminum Alloy"),
    ("ADC12 alloy", "ADC12 Aluminum Alloy"),
    ("AZ91D alloy", "AZ91D Magnesium Alloy"),
    ("thermal degradation of polymer", "Shear Thermal Degradation"),
    ("shear induced degradation", "Shear Thermal Degradation"),
    ("chain orientation", "Molecular Chain Orientation"),
    ("polymer chain alignment", "Molecular Chain Orientation"),
    ("air entrapment in die", "Air Entrapment"),
    ("gas entrainment", "Air Entrapment"),
    ("cavity temperature decrease", "Filling Temperature Drop"),
    ("melt temperature loss", "Filling Temperature Drop"),
    ("solid phase fraction", "Solid Fraction"),
    ("fraction of solid", "Solid Fraction"),
    ("eutectic Si morphology", "Eutectic Silicon Phase"),
    ("SDAS in aluminum", "Secondary Dendrite Arm Spacing"),
    ("solution treatment strengthening", "Solid Solution Strengthening"),
    ("precipitation hardening", "Age Hardening Precipitation"),
    # ================= 3. 中文标准术语与工厂口语/俗称 (Chinese & Slang Variants, 155条) =================
    ("模温", "Mold Temperature"),
    ("注塑模温", "Mold Temperature"),
    ("模具预热温度", "Mold Temperature"),
    ("模温机设定", "Mold Temperature"),
    ("料温", "Melt Temperature"),
    ("熔胶温度", "Melt Temperature"),
    ("炮筒温度", "Melt Temperature"),
    ("射嘴温度", "Melt Temperature"),
    ("射胶压力", "Injection Pressure"),
    ("一压", "Injection Pressure"),
    ("注塑压强", "Injection Pressure"),
    ("一阶段注射压力", "Injection Pressure"),
    ("保压", "Packing Pressure"),
    ("二压", "Packing Pressure"),
    ("保压压强", "Packing Pressure"),
    ("二次补缩压力", "Packing Pressure"),
    ("二次保压时间", "Packing Time"),
    ("保压时长", "Packing Time"),
    ("打针时间", "Packing Time"),
    ("射速", "Injection Velocity"),
    ("打针速度", "Injection Velocity"),
    ("注塑速度", "Injection Velocity"),
    ("充型流速", "Injection Velocity"),
    ("螺杆转速", "Screw Rotation Speed"),
    ("熔胶转速", "Screw Rotation Speed"),
    ("马达转速", "Screw Rotation Speed"),
    ("背压压强", "Back Pressure"),
    ("熔胶背压", "Back Pressure"),
    ("塑化背压", "Back Pressure"),
    ("冷却时长", "Cooling Time"),
    ("定型时间", "Cooling Time"),
    ("开模前冷却时间", "Cooling Time"),
    ("一速速度", "Slow Shot Velocity"),
    ("慢压射", "Slow Shot Velocity"),
    ("慢速冲头速度", "Slow Shot Velocity"),
    ("料筒慢推速度", "Slow Shot Velocity"),
    ("二速速度", "Fast Shot Velocity"),
    ("快压射", "Fast Shot Velocity"),
    ("高速冲头流速", "Fast Shot Velocity"),
    ("二级压射速度", "Fast Shot Velocity"),
    ("增压", "Intensification Pressure"),
    ("三压", "Intensification Pressure"),
    ("锻造增压比压", "Intensification Pressure"),
    ("最终增压压力", "Intensification Pressure"),
    ("建压时长", "Pressure Rise Time"),
    ("升压时间", "Pressure Rise Time"),
    ("增压建压反应时间", "Pressure Rise Time"),
    ("抽真空度", "Cavity Vacuum Degree"),
    ("型腔真空压强", "Cavity Vacuum Degree"),
    ("真空机负压", "Cavity Vacuum Degree"),
    ("浇铸温度", "Pouring Temperature"),
    ("铝液浇注温度", "Pouring Temperature"),
    ("冲头位移行程", "Plunger Stroke"),
    ("压射行程位置", "Plunger Stroke"),
    ("发白", "Gate Blushing"),
    ("进料口发白", "Gate Blushing"),
    ("浇口白斑", "Gate Blushing"),
    ("浇口白化现象", "Gate Blushing"),
    ("料头泛白", "Gate Blushing"),
    ("银丝", "Silver Streaks"),
    ("银丝纹", "Silver Streaks"),
    ("水汽银纹", "Silver Streaks"),
    ("气孔缺陷", "Gas Porosity"),
    ("气体包风孔", "Gas Porosity"),
    ("针孔气眼", "Gas Porosity"),
    ("皮下气孔", "Gas Porosity"),
    ("缩水孔", "Shrinkage Porosity"),
    ("显微缩松", "Shrinkage Porosity"),
    ("凝固缩孔", "Shrinkage Porosity"),
    ("壁厚缩凹", "Sink Marks"),
    ("表面下陷", "Sink Marks"),
    ("局部缩水痕", "Sink Marks"),
    ("披锋", "Flash"),
    ("飞边毛刺", "Flash"),
    ("合模缝溢料", "Flash"),
    ("模具毛边", "Flash"),
    ("缺胶", "Short Shot"),
    ("欠注缺料", "Short Shot"),
    ("注不满", "Short Shot"),
    ("充填不足", "Short Shot"),
    ("冷隔接缝", "Cold Shut"),
    ("冷疤", "Cold Shut"),
    ("流痕冷隔", "Cold Shut"),
    ("夹渣冷接", "Cold Shut"),
    ("夹水纹", "Weld Lines"),
    ("熔接线", "Weld Lines"),
    ("结合线", "Weld Lines"),
    ("两股料流汇合痕", "Weld Lines"),
    ("翘曲", "Warpage"),
    ("弯曲变形", "Warpage"),
    ("制件扭曲", "Warpage"),
    ("内应力集中", "Residual Stress"),
    ("成型残余应力", "Residual Stress"),
    ("脱模应力", "Residual Stress"),
    ("预结晶晶粒", "Externally Solidified Crystals"),
    ("料筒初晶组织", "Externally Solidified Crystals"),
    ("预结晶缺陷带", "Externally Solidified Crystals"),
    ("表面流痕水波纹", "Flow Marks"),
    ("光泽不均流纹", "Flow Marks"),
    ("起泡脱皮", "Blistering"),
    ("表面鼓泡", "Blistering"),
    ("PC塑料", "Polycarbonate (PC)"),
    ("聚碳酸酯树脂", "Polycarbonate (PC)"),
    ("PC聚碳酸酯颗粒", "Polycarbonate (PC)"),
    ("亚克力", "Polymethyl Methacrylate (PMMA)"),
    ("有机玻璃", "Polymethyl Methacrylate (PMMA)"),
    ("聚甲基丙烯酸甲酯颗粒", "Polymethyl Methacrylate (PMMA)"),
    ("PP百折胶", "Polypropylene (PP)"),
    ("聚丙烯料", "Polypropylene (PP)"),
    ("PP塑料颗粒", "Polypropylene (PP)"),
    ("ABS胶件", "Acrylonitrile Butadiene Styrene (ABS)"),
    ("工程ABS塑料", "Acrylonitrile Butadiene Styrene (ABS)"),
    ("加纤尼龙66", "Polyamide 66 (PA66-GF30)"),
    ("30%玻纤增强PA66", "Polyamide 66 (PA66-GF30)"),
    ("AlSi10MnMg免热处理铝合金", "AlSi10MnMg Aluminum Alloy"),
    ("硅镁铝合金", "AlSi10MnMg Aluminum Alloy"),
    ("A380美标压铸铝", "A380 Aluminum Alloy"),
    ("A380铝锭", "A380 Aluminum Alloy"),
    ("ADC12日标压铸铝合金", "ADC12 Aluminum Alloy"),
    ("ADC12铝液", "ADC12 Aluminum Alloy"),
    ("AZ91D压铸镁合金", "AZ91D Magnesium Alloy"),
    ("AZ91D镁锭", "AZ91D Magnesium Alloy"),
    ("剪切过热降解", "Shear Thermal Degradation"),
    ("高温剪切热分解", "Shear Thermal Degradation"),
    ("高分子链断裂降解", "Shear Thermal Degradation"),
    ("分子取向冻结", "Molecular Chain Orientation"),
    ("分子链拉伸定向", "Molecular Chain Orientation"),
    ("高分子取向效应", "Molecular Chain Orientation"),
    ("压铸卷气", "Air Entrapment"),
    ("金属液卷气包风", "Air Entrapment"),
    ("高速紊流卷气", "Air Entrapment"),
    ("充型热损失", "Filling Temperature Drop"),
    ("型腔内熔汤降温", "Filling Temperature Drop"),
    ("充型末端激冷温降", "Filling Temperature Drop"),
    ("初生固相率", "Solid Fraction"),
    ("晶体固相质量分数", "Solid Fraction"),
    ("半固态固相率", "Solid Fraction"),
    ("共晶硅片状相", "Eutectic Silicon Phase"),
    ("共晶硅改性组织", "Eutectic Silicon Phase"),
    ("针状共晶硅", "Eutectic Silicon Phase"),
    ("二次枝晶臂间距", "Secondary Dendrite Arm Spacing"),
    ("枝晶间距SDAS", "Secondary Dendrite Arm Spacing"),
    ("枝晶粗化程度", "Secondary Dendrite Arm Spacing"),
    ("固溶热处理强化", "Solid Solution Strengthening"),
    ("高温固溶处理", "Solid Solution Strengthening"),
    ("时效析出硬化", "Age Hardening Precipitation"),
    ("人工时效强化相析出", "Age Hardening Precipitation"),
    ("T6热处理时效态", "Age Hardening Precipitation"),
    ("模具温度", "Mold Temperature"),
    ("熔体温度", "Melt Temperature"),
    ("注射压力", "Injection Pressure"),
    ("保压压力", "Packing Pressure"),
    ("注射速度", "Injection Velocity"),
    ("残余应力", "Residual Stress"),
    ("气孔", "Gas Porosity"),
    # ================= 4. 域外无关干扰词 (Negative Distractors / 阈值拦截测试, 50条) =================
    ("coffee machine", "coffee machine"),
    ("deep learning", "deep learning"),
    ("neural network", "neural network"),
    ("operating system", "operating system"),
    ("database index", "database index"),
    ("keyboard switch", "keyboard switch"),
    ("apple juice", "apple juice"),
    ("electric bicycle", "electric bicycle"),
    ("quantum computing", "quantum computing"),
    ("solar panel", "solar panel"),
    ("blockchain smart contract", "blockchain smart contract"),
    ("financial stock market", "financial stock market"),
    ("transformer attention mechanism", "transformer attention mechanism"),
    ("bluetooth headphone", "bluetooth headphone"),
    ("mountain bicycle frame", "mountain bicycle frame"),
    ("paper coffee cup", "paper coffee cup"),
    ("acoustic guitar string", "acoustic guitar string"),
    ("cotton t-shirt", "cotton t-shirt"),
    ("wooden dining table", "wooden dining table"),
    ("ceramic tea pot", "ceramic tea pot"),
    ("weather forecast algorithm", "weather forecast algorithm"),
    ("space satellite trajectory", "space satellite trajectory"),
    ("compiler optimization flag", "compiler optimization flag"),
    ("internet routing protocol", "internet routing protocol"),
    ("swimming pool water filter", "swimming pool water filter"),
    ("咖啡机", "咖啡机"),
    ("深度学习", "深度学习"),
    ("操作系统内核", "操作系统内核"),
    ("数据库索引", "数据库索引"),
    ("机械键盘轴体", "机械键盘轴体"),
    ("苹果果汁", "苹果果汁"),
    ("电动自行车", "电动自行车"),
    ("量子计算比特", "量子计算比特"),
    ("太阳能光伏板", "太阳能光伏板"),
    ("区块链智能合约", "区块链智能合约"),
    ("金融股票市场", "金融股票市场"),
    ("蓝牙无线耳机", "蓝牙无线耳机"),
    ("山地自行车", "山地自行车"),
    ("一次性纸杯", "一次性纸杯"),
    ("木质餐桌", "木质餐桌"),
    ("陶瓷茶壶", "陶瓷茶壶"),
    ("天气预报算法", "天气预报算法"),
    ("编译器优化级别", "编译器优化级别"),
    ("网络路由协议", "网络路由协议"),
    ("游泳池过滤器", "游泳池过滤器"),
    ("卷积神经网络", "卷积神经网络"),
    ("微服务架构网关", "微服务架构网关"),
    ("机器学习特征工程", "机器学习特征工程"),
    ("无人机飞控系统", "无人机飞控系统"),
    ("移动端操作系统界面", "移动端操作系统界面"),
]


total = len(TEST_ENTITIES)
canonical_hits = 0  # 类别1：标准词输入，直接命中自身
aligned_hits = 0  # 类别2：同义词/缩写/跨语言变体输入，成功吸附对齐到正确标准词
rejection_hits = 0  # 类别3：域外负例干扰词输入，成功被阈值拦截（保持原词未被错误吸附）
failures = []  # 记录所有失败 case: (raw, expected, actual, failure_type)


for idx, (raw, expected) in enumerate(TEST_ENTITIES, 1):
    actual = aligner.aligner(raw)

    # 判定分支 A：输入本身就是标准词
    if raw in aligner.canonical_entities:
        if actual == expected:
            canonical_hits += 1
            status = "[标准命中]"
        else:
            failures.append((raw, expected, actual, "标准词漂移"))
            status = "[对齐失败]"
    # 判定分支 B：输入是域外负样本（预期不吸附，保留原词）
    elif raw == expected:
        if actual == expected:
            rejection_hits += 1
            status = "[负例拒识]"
        else:
            failures.append((raw, expected, actual, "误吸附(假阳性)"))
            status = "[对齐失败]"
    # 判定分支 C：输入是别名/缩写/中文（预期吸附到目标标准词）
    else:
        if actual == expected:
            aligned_hits += 1
            status = "[同义吸附]"
        else:
            failure_type = "未达阈值漏对齐" if actual == raw else "错配到其他词"
            failures.append((raw, expected, actual, failure_type))
            status = "[对齐失败]"

    if idx <= 15 or idx % 50 == 0:
        print(
            f"[{idx:>3}/{total}] {status} 输入: '{raw}' ➔ 输出: '{actual}' (预期: '{expected}')"
        )

# 统计总指标
total_success = canonical_hits + aligned_hits + rejection_hits
overall_accuracy = (total_success / total) * 100

print("\n" + "=" * 75)
print("实体对齐准确率评测总览报告 (Entity Alignment Evaluation Report)")
print("=" * 75)
print(f"总测试样本数:   {total}")
print(
    f"  ├─ 标准词命中 (Canonical Hits):   {canonical_hits:>3} / 48  ({canonical_hits / 48 * 100:.1f}%)"
)
print(
    f"  ├─ 同义/跨语对齐 (Aligned Hits):    {aligned_hits:>3} / 302 ({aligned_hits / 302 * 100:.1f}%)"
)
print(
    f"  ├─ 负例拒识成功 (Rejection Hits):  {rejection_hits:>3} / 50  ({rejection_hits / 50 * 100:.1f}%)"
)
print(
    f"  └─ 对齐失败总数 (Failures):         {len(failures):>3} / {total} ({len(failures) / total * 100:.1f}%)"
)
print("-" * 75)
print(f"全局综合准确率 (Overall Accuracy):   {overall_accuracy:.2f}%")
print("=" * 75)

if failures:
    print(f"\n失败用例明细清单 (共 {len(failures)} 条):")
    print(
        f"{'序号':<4} | {'失败类型':<14} | {'输入原始词':<25} | {'预期标准词':<30} | {'实际输出'}"
    )
    print("-" * 90)
    for i, (r, exp, act, ftype) in enumerate(failures, 1):
        print(f"{i:<4} | {ftype:<14} | {r:<25} | {exp:<30} | {act}")
